/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as ProjectsProjectIdWeeksRouteImport } from './routes/projects/$projectId/weeks'
import { Route as ProjectsProjectIdOverviewRouteImport } from './routes/projects/$projectId/overview'
import { Route as ProjectsProjectIdJourneyRouteImport } from './routes/projects/$projectId/journey'
import { Route as ProjectsProjectIdCampaignsRouteImport } from './routes/projects/$projectId/campaigns'
import { Route as ProjectsProjectIdArtifactsRouteImport } from './routes/projects/$projectId/artifacts'
import { Route as CampaignsCampaignIdStepRouteImport } from './routes/campaigns/$campaignId.$step'
import { Route as ProjectsProjectIdCampaignsIndexRouteImport } from './routes/projects/$projectId/campaigns/index'
import { Route as ProjectsProjectIdBriefingSectionIdRouteImport } from './routes/projects/$projectId/briefing/$sectionId'
import { Route as ProjectsProjectIdCampaignsCampaignIdStageIdRouteImport } from './routes/projects/$projectId/campaigns/$campaignId/$stageId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdWeeksRoute = ProjectsProjectIdWeeksRouteImport.update({
  id: '/weeks',
  path: '/weeks',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdOverviewRoute =
  ProjectsProjectIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdJourneyRoute =
  ProjectsProjectIdJourneyRouteImport.update({
    id: '/journey',
    path: '/journey',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCampaignsRoute =
  ProjectsProjectIdCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdArtifactsRoute =
  ProjectsProjectIdArtifactsRouteImport.update({
    id: '/artifacts',
    path: '/artifacts',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const CampaignsCampaignIdStepRoute = CampaignsCampaignIdStepRouteImport.update({
  id: '/campaigns/$campaignId/$step',
  path: '/campaigns/$campaignId/$step',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdCampaignsIndexRoute =
  ProjectsProjectIdCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdCampaignsRoute,
  } as any)
const ProjectsProjectIdBriefingSectionIdRoute =
  ProjectsProjectIdBriefingSectionIdRouteImport.update({
    id: '/briefing/$sectionId',
    path: '/briefing/$sectionId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCampaignsCampaignIdStageIdRoute =
  ProjectsProjectIdCampaignsCampaignIdStageIdRouteImport.update({
    id: '/$campaignId/$stageId',
    path: '/$campaignId/$stageId',
    getParentRoute: () => ProjectsProjectIdCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/campaigns/$campaignId/$step': typeof CampaignsCampaignIdStepRoute
  '/projects/$projectId/artifacts': typeof ProjectsProjectIdArtifactsRoute
  '/projects/$projectId/campaigns': typeof ProjectsProjectIdCampaignsRouteWithChildren
  '/projects/$projectId/journey': typeof ProjectsProjectIdJourneyRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/projects/$projectId/weeks': typeof ProjectsProjectIdWeeksRoute
  '/projects/$projectId/briefing/$sectionId': typeof ProjectsProjectIdBriefingSectionIdRoute
  '/projects/$projectId/campaigns/': typeof ProjectsProjectIdCampaignsIndexRoute
  '/projects/$projectId/campaigns/$campaignId/$stageId': typeof ProjectsProjectIdCampaignsCampaignIdStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/campaigns/$campaignId/$step': typeof CampaignsCampaignIdStepRoute
  '/projects/$projectId/artifacts': typeof ProjectsProjectIdArtifactsRoute
  '/projects/$projectId/journey': typeof ProjectsProjectIdJourneyRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/projects/$projectId/weeks': typeof ProjectsProjectIdWeeksRoute
  '/projects/$projectId/briefing/$sectionId': typeof ProjectsProjectIdBriefingSectionIdRoute
  '/projects/$projectId/campaigns': typeof ProjectsProjectIdCampaignsIndexRoute
  '/projects/$projectId/campaigns/$campaignId/$stageId': typeof ProjectsProjectIdCampaignsCampaignIdStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/healthz': typeof HealthzRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/campaigns/$campaignId/$step': typeof CampaignsCampaignIdStepRoute
  '/projects/$projectId/artifacts': typeof ProjectsProjectIdArtifactsRoute
  '/projects/$projectId/campaigns': typeof ProjectsProjectIdCampaignsRouteWithChildren
  '/projects/$projectId/journey': typeof ProjectsProjectIdJourneyRoute
  '/projects/$projectId/overview': typeof ProjectsProjectIdOverviewRoute
  '/projects/$projectId/weeks': typeof ProjectsProjectIdWeeksRoute
  '/projects/$projectId/briefing/$sectionId': typeof ProjectsProjectIdBriefingSectionIdRoute
  '/projects/$projectId/campaigns/': typeof ProjectsProjectIdCampaignsIndexRoute
  '/projects/$projectId/campaigns/$campaignId/$stageId': typeof ProjectsProjectIdCampaignsCampaignIdStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/healthz'
    | '/projects'
    | '/projects/$projectId'
    | '/dashboard/'
    | '/projects/'
    | '/campaigns/$campaignId/$step'
    | '/projects/$projectId/artifacts'
    | '/projects/$projectId/campaigns'
    | '/projects/$projectId/journey'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/weeks'
    | '/projects/$projectId/briefing/$sectionId'
    | '/projects/$projectId/campaigns/'
    | '/projects/$projectId/campaigns/$campaignId/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/healthz'
    | '/projects/$projectId'
    | '/dashboard'
    | '/projects'
    | '/campaigns/$campaignId/$step'
    | '/projects/$projectId/artifacts'
    | '/projects/$projectId/journey'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/weeks'
    | '/projects/$projectId/briefing/$sectionId'
    | '/projects/$projectId/campaigns'
    | '/projects/$projectId/campaigns/$campaignId/$stageId'
  id:
    | '__root__'
    | '/'
    | '/healthz'
    | '/projects'
    | '/projects/$projectId'
    | '/dashboard/'
    | '/projects/'
    | '/campaigns/$campaignId/$step'
    | '/projects/$projectId/artifacts'
    | '/projects/$projectId/campaigns'
    | '/projects/$projectId/journey'
    | '/projects/$projectId/overview'
    | '/projects/$projectId/weeks'
    | '/projects/$projectId/briefing/$sectionId'
    | '/projects/$projectId/campaigns/'
    | '/projects/$projectId/campaigns/$campaignId/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthzRoute: typeof HealthzRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  CampaignsCampaignIdStepRoute: typeof CampaignsCampaignIdStepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/weeks': {
      id: '/projects/$projectId/weeks'
      path: '/weeks'
      fullPath: '/projects/$projectId/weeks'
      preLoaderRoute: typeof ProjectsProjectIdWeeksRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/overview': {
      id: '/projects/$projectId/overview'
      path: '/overview'
      fullPath: '/projects/$projectId/overview'
      preLoaderRoute: typeof ProjectsProjectIdOverviewRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/journey': {
      id: '/projects/$projectId/journey'
      path: '/journey'
      fullPath: '/projects/$projectId/journey'
      preLoaderRoute: typeof ProjectsProjectIdJourneyRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/campaigns': {
      id: '/projects/$projectId/campaigns'
      path: '/campaigns'
      fullPath: '/projects/$projectId/campaigns'
      preLoaderRoute: typeof ProjectsProjectIdCampaignsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/artifacts': {
      id: '/projects/$projectId/artifacts'
      path: '/artifacts'
      fullPath: '/projects/$projectId/artifacts'
      preLoaderRoute: typeof ProjectsProjectIdArtifactsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/campaigns/$campaignId/$step': {
      id: '/campaigns/$campaignId/$step'
      path: '/campaigns/$campaignId/$step'
      fullPath: '/campaigns/$campaignId/$step'
      preLoaderRoute: typeof CampaignsCampaignIdStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/campaigns/': {
      id: '/projects/$projectId/campaigns/'
      path: '/'
      fullPath: '/projects/$projectId/campaigns/'
      preLoaderRoute: typeof ProjectsProjectIdCampaignsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdCampaignsRoute
    }
    '/projects/$projectId/briefing/$sectionId': {
      id: '/projects/$projectId/briefing/$sectionId'
      path: '/briefing/$sectionId'
      fullPath: '/projects/$projectId/briefing/$sectionId'
      preLoaderRoute: typeof ProjectsProjectIdBriefingSectionIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/campaigns/$campaignId/$stageId': {
      id: '/projects/$projectId/campaigns/$campaignId/$stageId'
      path: '/$campaignId/$stageId'
      fullPath: '/projects/$projectId/campaigns/$campaignId/$stageId'
      preLoaderRoute: typeof ProjectsProjectIdCampaignsCampaignIdStageIdRouteImport
      parentRoute: typeof ProjectsProjectIdCampaignsRoute
    }
  }
}

interface ProjectsProjectIdCampaignsRouteChildren {
  ProjectsProjectIdCampaignsIndexRoute: typeof ProjectsProjectIdCampaignsIndexRoute
  ProjectsProjectIdCampaignsCampaignIdStageIdRoute: typeof ProjectsProjectIdCampaignsCampaignIdStageIdRoute
}

const ProjectsProjectIdCampaignsRouteChildren: ProjectsProjectIdCampaignsRouteChildren =
  {
    ProjectsProjectIdCampaignsIndexRoute: ProjectsProjectIdCampaignsIndexRoute,
    ProjectsProjectIdCampaignsCampaignIdStageIdRoute:
      ProjectsProjectIdCampaignsCampaignIdStageIdRoute,
  }

const ProjectsProjectIdCampaignsRouteWithChildren =
  ProjectsProjectIdCampaignsRoute._addFileChildren(
    ProjectsProjectIdCampaignsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdArtifactsRoute: typeof ProjectsProjectIdArtifactsRoute
  ProjectsProjectIdCampaignsRoute: typeof ProjectsProjectIdCampaignsRouteWithChildren
  ProjectsProjectIdJourneyRoute: typeof ProjectsProjectIdJourneyRoute
  ProjectsProjectIdOverviewRoute: typeof ProjectsProjectIdOverviewRoute
  ProjectsProjectIdWeeksRoute: typeof ProjectsProjectIdWeeksRoute
  ProjectsProjectIdBriefingSectionIdRoute: typeof ProjectsProjectIdBriefingSectionIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdArtifactsRoute: ProjectsProjectIdArtifactsRoute,
  ProjectsProjectIdCampaignsRoute: ProjectsProjectIdCampaignsRouteWithChildren,
  ProjectsProjectIdJourneyRoute: ProjectsProjectIdJourneyRoute,
  ProjectsProjectIdOverviewRoute: ProjectsProjectIdOverviewRoute,
  ProjectsProjectIdWeeksRoute: ProjectsProjectIdWeeksRoute,
  ProjectsProjectIdBriefingSectionIdRoute:
    ProjectsProjectIdBriefingSectionIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthzRoute: HealthzRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  CampaignsCampaignIdStepRoute: CampaignsCampaignIdStepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
